Sepia_plots:
 CO2 emissions by sector: true
 CO2 emissions by source: true
 Cumulative CO2 emissions by sector: true
 Cumulative CO2 emissions by source: true
 Sankey diagram: true
 Carbon Sankey diagram: true
 Renewable energy share: true
 Final energy consumption by origin: true
 Share of domestic production: true
 Final energy consumption by each sector: true
 Mix of secondary energies: true
 Final energy consumption by carrier for each sector: true
 
Pypsa_plots:
 Sectoral Demands: true
 Annual Costs: true
 Annual Investment Costs: true
 Capacities: true
 Storage Capacities: true
 Heat Dispatch Winter: true
 Heat Dispatch Summer: true
 Power Dispatch Winter: true
 Power Dispatch Summer: true
 Map Plots: true
 H2 Map Plots: true
 Gas Map Plots: true
 
Scenario_plots:
 Annual Costs: true
 Annual Investment Costs: true
 Cummulative Investment Costs: true
 Capacities: true
 Storage Capacities: true
 Scenarios Demands Comparison: true
 Scenarios VRE Capacities Comparison: true
 Scenario Flexibility Capacities: true
 Scenarios Costs Comparison: true
 Historic Generation Comparison: true
 
