# SPDX-FileCopyrightText: : 2017-2024 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: MIT

name: pypsa-eur
channels:
- conda-forge
- bioconda
dependencies:
- python=3.11.9
- pip

- atlite=0.2.12
- pypsa=0.27.0
- linopy=0.3.4
- dask

  # Dependencies of the workflow itself
- xlrd
- openpyxl!=3.1.1
- pycountry
- seaborn=0.13.2
- snakemake-minimal>=8.5
- memory_profiler
- yaml
- pytables
- lxml
- powerplantmatching>=0.5.5,!=0.5.9
- numpy
- pandas=2.2.0
- geopandas=0.14.3
- geopandas-base=0.14.3
- xarray=2024.2.0
- rioxarray
- netcdf4
- networkx
- scipy
- glpk
- shapely>=2.0
- pyscipopt
- matplotlib=3.8.2
- proj
- fiona=1.9.5
- country_converter
- geopy
- tqdm
- pytz
- tabula-py
- pyxlsb
- graphviz
- pre-commit
- plotly
- panel

  # Keep in conda environment when calling ipython
- ipython

  # GIS dependencies:
- cartopy
- descartes
- rasterio!=1.2.10


- pip:
  - tsam==2.3.1
  - highspy==1.5.3
  - snakemake-storage-plugin-http
  - snakemake-executor-plugin-slurm
  - snakemake-executor-plugin-cluster-generic
  - highspy
